### PR TITLE
ignore errors in checkmode

### LINKED ISSUE #27: Ensure start and enable example.service error is ignored in check mode
When trying out your new snapclient structure with --check and --diff my playbook cancelled after `TASK [snapclient : Enable and start snapclient@ services]` as it failed because it couldn't check if it would work as the services don't exist yet:

```
TASK [snapclient : Enable and start snapclient@ services] ****************************************************************************************************************************************************
failed: [pi2] (item=pi2) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "pi2", "snapclient_sink": "dmix:CARD=sndrpihifiberry,DEV=0", "snapclient_snapserver": "pidev.example.net"}, "msg": "Could not find the requested service snapclient@pi2.service: host"}
failed: [pi3] (item=pi2) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "pi2", "snapclient_sink": "dmix:CARD=sndrpihifiberry,DEV=0", "snapclient_snapserver": "pidev.example.net"}, "msg": "Could not find the requested service snapclient@pi2.service: host"}
failed: [pi5] (item=pi2) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "pi2", "snapclient_sink": "dmix:CARD=sndrpihifiberry,DEV=0", "snapclient_snapserver": "pidev.example.net"}, "msg": "Could not find the requested service snapclient@pi2.service: host"}
failed: [pi4] (item=pi2) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "pi2", "snapclient_sink": "dmix:CARD=sndrpihifiberry,DEV=0", "snapclient_snapserver": "pidev.example.net"}, "msg": "Could not find the requested service snapclient@pi2.service: host"}
```

So we should make sure that every task that relies on a file or systemd unit being present either is handled in check mode so the check mode runs through

### PR DESCRIPTION
**Pull request by nis65**
Found another glitch. Fixes #27

### CODE REVIEW

**Comment by nis65** [comment]
Ready to merge :smile:

**Comment by nis65** [comment]
fixes #27

**Review by Daenou — APPROVED** [review]
Works for me

**Comment by Daenou** [comment]
@nis65 Please review my changes and merge

**Comment by nis65** [comment]
Tested successfully with `--check` only on a fresh bullseye image. Found some more, but with latest commit 82a7c9b you can run `--check` with all errors ignored that would cause the playbook to abort. Merging.

**Pull request merged**
