### PR TITLE
fix: wlan ipv6-if nodad, generic local fw ports, raspotify mDNS workaround for camper

### PR DESCRIPTION
**Pull request by nis65**

### CODE REVIEW

**Comment by nis65** [comment]
A note: I "just" wanted quickly add "raspotify" to my camper setup and I discovered
that the raspotify mDNS announcements are seen on the uplink network only, not on the ap0 side. 

Experimenting with the raspotify config setting `LIBRESPOT_ZEROCONF_INTERFACE` did not help,
the only working workaround was to make the local `avahi-daemon` announce raspotify a 2nd time. 
This needs a fixed port number.

Using a configured (and not randomly chosen at startup) port is also needed in the camper setup as
the `uplink` role (needed for raspotify anyway to get some music) firewalls the access to the raspi
strictly and we need to explicitly unfirewall the raspotify port.

TODO: Announce IPv6 too

**Comment by nis65** [comment]
what I see now (being connected to the `ap0` WLAN:
~~~
$ LANG=C avahi-browse -vart
Server version: avahi 0.7; Host name: lambda.local
E Ifce Prot Name                                          Type                 Domain
+ wlp1s0 IPv6 mpd@camper                                    Music Player Daemon  local
+ wlp1s0 IPv4 mpd@camper                                    Music Player Daemon  local
+ wlp1s0 IPv6 Spotify on camper                             _spotify-connect._tcp local
+ wlp1s0 IPv4 Spotify on camper                             _spotify-connect._tcp local
= wlp1s0 IPv6 mpd@camper                                    Music Player Daemon  local
   hostname = [camper.local]
   address = [fd86:7b08:fef2::1]
   port = [6600]
   txt = []
= wlp1s0 IPv4 mpd@camper                                    Music Player Daemon  local
   hostname = [camper.local]
   address = [172.26.0.1]
   port = [6600]
   txt = []
= wlp1s0 IPv6 Spotify on camper                             _spotify-connect._tcp local
   hostname = [camper.local]
   address = [fd86:7b08:fef2::1]
   port = [12345]
   txt = ["VERSION=1.0" "CPath=/"]
= wlp1s0 IPv4 Spotify on camper                             _spotify-connect._tcp local
   hostname = [camper.local]
   address = [172.26.0.1]
   port = [12345]
   txt = ["VERSION=1.0" "CPath=/"]
: Cache exhausted
: All for now
~~~

* `mpd` zeroconf announcements are just working on WLAN
* `spotify` stuff only shown in WLAN with avahi-daemon service file
* when stopping `firewalld` (no masquerading any more, but also no filtering any more), both the `mpd` and `spotify` stuff appears on the LAN uplink network (even without the addition avahi service file)

:shrug:

**Comment by nis65** [comment]
@Daenou finally, I am happy with this MR. Multiple bugs fixed that I discovered after our latest merge session:
* With IPv6 on the WLAN interface, you need to disable `dad`: As this is the first interface, duplicate address detection won't work there ever and the systemd `networking` will be `starting` for ever.
* Running raspotify on a router (or on a WLAN interface?) kills mDNS at least on one interface - but this is required for a good user experience. Furthermore, on a router all local ports are closed by default, so in this setup the raspotify port must be unfirewalled. Solution/workaround found and implemented.

**Review by Daenou — APPROVED** [review]
LGTM 🚀

**Pull request merged**
